name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Initialise cache
      uses: actions/cache@v2
      with:
           path: |
               ~/.cargo/registry
               ~/.cargo/git
               target
           key: ${{runner.os}}-cargo-${{hashFile("**/Cargo.lock")}}

    - name: Install OS dependencies
      run: sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
